# Generated by Django 2.2.3 on 2020-04-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('tag', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('abort', models.TextField(default='')),
                ('ended', models.TextField(default='')),
                ('error', models.TextField(default='')),
                ('pause', models.TextField(default='')),
                ('play', models.TextField(default='')),
                ('playing', models.TextField(default='')),
                ('seeked', models.TextField(default='')),
                ('seeking', models.TextField(default='')),
                ('timeupdate', models.TextField(default='')),
                ('volumechange', models.TextField(default='')),
                ('waiting', models.TextField(default='')),
                ('rating', models.TextField(default='')),
                ('timestopped', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('date', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(default='')),
                ('vidCategory', models.TextField(default='')),
                ('vidTag', models.TextField(default='')),
                ('vidURL', models.TextField(default='')),
            ],
        ),
    ]
